### ISSUE TITLE
Conduct UAT of eCR data store

### ISSUE THREAD

**Issue by pkchau-skylight** [CDCgov/phdi-google-cloud#106]
[UAT Plan
](https://docs.google.com/document/d/15bFc0cHK6mtPlPJaGd6AQcQ_73oXQVWNHTUYP45fTYA/edit#bookmark=id.im6zcdl7pxiu)
- [x] Schedule UAT session w/ Allene
- [x] Conduct UAT session w/ Allene
- [x] Check in on async UAT over the week of August 7-11
- [ ] Schedule & prep for UAT session w/ Jordan
- [ ] Conduct UAT session w/ Jordan
- [ ] Schedule & prep for UAT session w/ Hepatitis Team
- [ ] Conduct UAT session w/ Hepatitis Team
- [ ] Schedule & prep for UAT session w/ PJ
- [ ] Conduct UAT session w/ PJ

**Comment by DanPaseltiner** [comment]
Messages Jordan on LAC Teams about time to meet on Hep A datamart. Waiting to hear back.
