### ISSUE TITLE
Review revised Summary Findings report 

### ISSUE THREAD

**Issue by mattmgoldberg** [CDCgov/phdi-google-cloud#109]
Amrita to review "Deploying our Pipeline in LAC’s Data Environment" section and new content under "What We Learned"

**Comment by DanPaseltiner** [comment]
@mattmgoldberg is this complete now?

**Comment by mattmgoldberg** [comment]
That particular review is done. We'll need a review of the additional metrics analysis section, but that can be a different ticket I write later when we can shift focus back to summary findings
