### ISSUE TITLE
Add additional tests MPI - Verify multiple given names

### ISSUE THREAD

**Issue by BradySkylight** [CDCgov/phdi-google-cloud#127]
Write additional tests in test_mpi.py

1- Ensure the basic query is getting all instances of names (given names)
2- Ensure that the order of the names is correct based upon the given name index

**Comment by robertmitchellv** [comment]
i can't assign myself this one in zenhub but will be picking it up

**Comment by BradySkylight** [comment]
> i can't assign myself this one in zenhub but will be picking it up

I assigned it to you! ;)

**Comment by robertmitchellv** [comment]
finished this one; it's in the big MPI branch on `phdi` in `phdi/tests/linkage/test_mpi.py`
